export const DUMMY = {
  name: "프론트엔드 개발자 취업",
  priorityRatio: 100,
  scheduledTotalTime: 60,
  executedTotalTime: 40,
  children: [
    {
      name: "제품 개발",
      priorityRatio: 25,
      scheduledTotalTime: 15,
      executedTotalTime: 20,
      children: [
        {
          name: "개인 프로젝트 FocusTree",
          scheduledTotalTime: 10.5,
          priorityRatio: 70,
          executedTotalTime: 15,
        },
        {
          name: "데브코스 2차팀 FE 프로젝트",
          scheduledTotalTime: 2.25,
          priorityRatio: 15,
          executedTotalTime: 5,
        },
        {
          name: "개인 프로젝트 my-wiki",
          scheduledTotalTime: 2.25,
          priorityRatio: 15,
          executedTotalTime: 0,
        },
      ],
    },
    {
      name: "실무 기술의 원리",
      priorityRatio: 25,
      scheduledTotalTime: 15,
      executedTotalTime: 10,
      children: [
        {
          name: "React",
          priorityRatio: 40,
          scheduledTotalTime: 6,
          executedTotalTime: 4,
        },
        {
          name: "CSS",
          priorityRatio: 20,
          scheduledTotalTime: 3,
          executedTotalTime: 3,
        },
        {
          name: "JavaScript",
          priorityRatio: 15,
          scheduledTotalTime: 2.25,
          executedTotalTime: 0,
        },
        {
          name: "React-query",
          priorityRatio: 10,
          scheduledTotalTime: 1.5,
          executedTotalTime: 2,
        },
        {
          name: "Zustand",
          priorityRatio: 5,
          scheduledTotalTime: 0.75,
          executedTotalTime: 0,
        },
        {
          name: "TailwindCSS",
          priorityRatio: 5,
          scheduledTotalTime: 0.75,
          executedTotalTime: 1,
        },
        {
          name: "TypeScript",
          priorityRatio: 5,
          scheduledTotalTime: 0.75,
          executedTotalTime: 0,
        },
      ],
    },
    {
      name: "실무 기본기",
      priorityRatio: 20,
      scheduledTotalTime: 12,
      executedTotalTime: 5,
      children: [
        {
          name: "웹 브라우저",
          priorityRatio: 30,
          scheduledTotalTime: 3.6,
          executedTotalTime: 0,
        },
        {
          name: "모바일 대응",
          priorityRatio: 25,
          scheduledTotalTime: 3,
          executedTotalTime: 3,
        },
        {
          name: "API",
          priorityRatio: 20,
          scheduledTotalTime: 2.4,
          executedTotalTime: 0,
        },
        {
          name: "보안",
          priorityRatio: 15,
          scheduledTotalTime: 1.8,
          executedTotalTime: 2,
        },
        {
          name: "SEO",
          priorityRatio: 10,
          scheduledTotalTime: 1.2,
          executedTotalTime: 0,
        },
      ],
    },
    {
      name: "CS 기본기",
      priorityRatio: 15,
      scheduledTotalTime: 9,
      executedTotalTime: 3,
      size: 1759,
      children: [
        {
          name: "네트워크",
          priorityRatio: 40,
          scheduledTotalTime: 3.6,
          executedTotalTime: 2,
        },
        {
          name: "운영체제",
          priorityRatio: 30,
          scheduledTotalTime: 2.7,
          executedTotalTime: 1,
        },
        {
          name: "데이터베이스",
          priorityRatio: 20,
          scheduledTotalTime: 1.8,
          executedTotalTime: 0,
        },
        {
          name: "컴퓨터 구조",
          priorityRatio: 10,
          scheduledTotalTime: 0.9,
          executedTotalTime: 0,
        },
      ],
    },
    {
      name: "코딩 테스트 기본기",
      priorityRatio: 10,
      scheduledTotalTime: 6,
      executedTotalTime: 2,
      size: 2165,
      children: [
        {
          name: "구현/시뮬레이션/완전탐색",
          priorityRatio: 50,
          scheduledTotalTime: 3,
          executedTotalTime: 2,
        },
        {
          name: "그래프 탐색",
          priorityRatio: 30,
          scheduledTotalTime: 1.8,
          executedTotalTime: 0,
        },
        {
          name: "동적 프로그래밍",
          priorityRatio: 20,
          scheduledTotalTime: 1.2,
          executedTotalTime: 0,
        },
      ],
    },
    {
      name: "구직 활동",
      priorityRatio: 5,
      scheduledTotalTime: 3,
      executedTotalTime: 0,
      children: [
        {
          name: "공고 수집 및 선별",
          priorityRatio: 20,
          scheduledTotalTime: 3,
          executedTotalTime: 0,
        },
        {
          name: "서류 작성",
          priorityRatio: 20,
          scheduledTotalTime: 0,
          executedTotalTime: 0,
        },
        {
          name: "코딩 테스트 응시",
          priorityRatio: 20,
          scheduledTotalTime: 0,
          executedTotalTime: 0,
        },
        {
          name: "기술 면접",
          priorityRatio: 20,
          scheduledTotalTime: 0,
          executedTotalTime: 0,
        },
        {
          name: "기술 면접 회고",
          priorityRatio: 20,
          scheduledTotalTime: 0,
          executedTotalTime: 0,
        },
      ],
    },
  ],
} as const;
